version: "3"
services:
  zagnok_api:
    container_name: zagnok_api
    build:
      context: ./docker/
      dockerfile: zagnok_api.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file: .env

  http:
    container_name: zagnok_http
    build: 
      context: ./docker/
      dockerfile: zagnok_http.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "80:80"

  db:
    container_name: zagnok_db
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=2Cf$YG*/cApC#_*?2-vU%!QX"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    ports:
      - "33060:3306"

volumes:
  dbdata: